channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - pip=22.3.1
  - pip:
      - azureml-defaults==1.48.0
      - azureml-sdk==1.48.0
      - python pytest==7.1.2
      - mlflow==1.27.0
      - pandas==1.4.3
      - sklearn==0.0
      - scikit-learn==1.1.1
name: mslearn-mlops