name: Manually trigger an Azure Machine Learning job

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: az login --service-principal -u ${{secrets.CLIENT_ID}} -p ${{secrets.CLIENT_SECRET}} --tenant ${{secrets.TENANT_ID}}
    - name: Register the dataset
      run: az ml data create --path ./experimentation/data/diabetes-dev.csv --name diabetes-dev --workspace-name leonardazureml --type uri_file
    - name: Trigger Azure Machine Learning job --workspace-name leonardazureml
      run: az ml job create --file src/job.yml


