name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  workspace-name: mlpromptflow # name of the Azure Machine Learning workspace
  resource-group: ah-openai-rg # name of the Azure resource group

permissions:
  id-token: write
  contents: read

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job.yml --workspace-name ${{ env.workspace-name }} --resource-group ${{ env.resource-group }}


