name: Manually trigger an Azure Machine Learning job

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: leonard_enablement
      WORKSPACE_NAME: leonardazureml
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Start compute instance if not already running
      run: |
        # Get the state of the compute instance
        state=$(az ml compute show --name smolboi --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --query state -o tsv)
        # If the compute instance is not running, start it
        if [ "$state" != "Running" ]; then
          az ml compute start --name smolboi --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
        fi
    - name: Trigger Azure Machine Learning job
      run: az ml job create --file src/job.yml --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
    - name: Stop compute instance
      run: |
        az ml compute stop --name smolboi --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
